# Generated by Django 5.1.5 on 2025-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
