# Generated by Django 5.1.5 on 2025-01-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_jobrotation_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='Backend.department'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='process',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_processes', to='Backend.employee'),
        ),
    ]
