# Generated by Django 5.1.5 on 2025-02-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_process_department_remove_process_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PassWoRd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='UserNaMe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
