# Generated by Django 5.1.5 on 2025-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_employee_password_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PassWoRd',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='UserNaMe',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
