# Generated by Django 5.1.5 on 2025-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_employee_password_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PassWoRd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='UserNaMe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
