# Generated by Django 5.1.5 on 2025-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrotation',
            name='new_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobrotation',
            name='shift_rotation',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=10),
        ),
    ]
