# Generated by Django 5.1.5 on 2025-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_jobrotation_new_salary_jobrotation_shift_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrotation',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('day', 'Day Shift (9:30 AM - 6:00 PM)'), ('night', 'Night Shift (11:00 PM - 7:30 AM)')], default='day', max_length=10),
        ),
    ]
