# Generated by Django 5.1.5 on 2025-02-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_remove_jobrotation_approved_by_employee_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrotation',
            old_name='from_role',
            new_name='new_position',
        ),
        migrations.RemoveField(
            model_name='jobrotation',
            name='shift_rotation',
        ),
        migrations.RemoveField(
            model_name='jobrotation',
            name='to_role',
        ),
        migrations.AddField(
            model_name='jobrotation',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrotation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.employee'),
        ),
        migrations.AlterField(
            model_name='jobrotation',
            name='new_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrotation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrotation',
            name='rotation_date',
            field=models.DateField(),
        ),
    ]
