# Generated by Django 5.1.5 on 2025-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
