# Generated by Django 5.1.5 on 2025-02-11 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_employee_location_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rotation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='JobRotation',
        ),
    ]
