# Generated by Django 5.1.5 on 2025-02-11 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_employee_reason_employee_rotation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rotation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
