# Generated by Django 5.1.5 on 2025-02-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_alter_employee_rotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rotation_date',
            field=models.DateField(),
        ),
    ]
