# Generated by Django 5.1.5 on 2025-02-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
