# Generated by Django 5.1.5 on 2025-02-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_remove_register_email_remove_register_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.register'),
        ),
    ]
